version: '3.8'
services:
  security-service:
    image: security-service:latest
    ports:
      - "8080:8080"
    networks:
      - microservices-network

  report-service:
    image: report-service:latest
    ports:
      - "8081:8081"
    networks:
      - microservices-network

  data-service:
    image: data-service:latest
    ports:
      - "8082:8082"
    networks:
      - microservices-network

  messaging-service:
    image: messaging-service:latest
    ports:
      - "8083:8083"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge